services:
  app:
    environment:
      EVENTRELAY_WORKER_MAX_IN_FLIGHT_PER_DESTINATION: "10"
      EVENTRELAY_WORKER_BATCH_SIZE: "500"
      EVENTRELAY_WORKER_POLL_INTERVAL: "1s"
  worker-2:
    environment:
      EVENTRELAY_WORKER_MAX_IN_FLIGHT_PER_DESTINATION: "10"
      EVENTRELAY_WORKER_BATCH_SIZE: "500"
      EVENTRELAY_WORKER_POLL_INTERVAL: "1s"
