# Datasource (Dev Services for Postgres)
quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.image-name=postgres:16

# Flyway migrations
quarkus.flyway.migrate-at-start=true

# Swagger UI (dev only)
%dev.quarkus.swagger-ui.always-include=true
